application: worldsprojectorg
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img
  
- url: /javascript
  static_dir: javascript
  
- url: /css
  static_dir: css

- url: /fluxware/.*
  script: fluxware/index.py

- url: /.*
  script: index.py
